# Generated by Django 5.1.7 on 2025-03-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='products/default.jpg', upload_to='products/'),
        ),
    ]
